eureka:
  instance:
    hostname: localhost
  client:
    # registerWithEureka和fetchRegistry设置false表明是eureka 的 server端
    registerWithEureka: false #是否向服务注册中心注册自己
    fetchRegistry: false #是否检索服务
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


#自我保护模式关闭  --- 线上不可关闭
  #保护模式主要用于一组客户端和Eureka Server之间存在网络分区场景下的保护。一旦进入保护模式，Eureka Server将会尝试保护其服务注册表中的信息，不再删除服务注册表中的数据
  server:
    enableSelfPreservation: false